
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.VBox vbox1;

	private global::Gtk.Frame frame_input;

	private global::Gtk.Alignment GtkAlignment;

	private global::Gtk.VBox vbox2;

	private global::Gtk.HBox hbox1;

	private global::Gtk.Label label3;

	private global::Gtk.Label label1;

	private global::Gtk.Entry inputPublications;

	private global::Gtk.Button inputPublicationsSelect;

	private global::Gtk.HBox hbox2;

	private global::Gtk.Label label4;

	private global::Gtk.Label label2;

	private global::Gtk.Entry inputKnownLocations;

	private global::Gtk.Button inputKnownLocationsSelect;

	private global::Gtk.HBox hbox3;

	private global::Gtk.Label label5;

	private global::Gtk.Label label6;

	private global::Gtk.Entry inputGeoCoderKey;

	private global::Gtk.CheckButton inputRetryGeoCoding;

	private global::Gtk.Label GtkLabel3;

	private global::Gtk.Frame frame3;

	private global::Gtk.Alignment GtkAlignment1;

	private global::Gtk.VBox vbox3;

	private global::Gtk.HBox hbox7;

	private global::Gtk.Button buttonStart;

	private global::Gtk.Button buttonStop;

	private global::Gtk.ScrolledWindow GtkScrolledWindow;

	private global::Gtk.TextView messages;

	private global::Gtk.Label GtkLabel6;

	private global::Gtk.Frame frame_output;

	private global::Gtk.Alignment GtkAlignment2;

	private global::Gtk.VBox vbox4;

	private global::Gtk.HBox hbox4;

	private global::Gtk.VBox vbox7;

	private global::Gtk.Label label16;

	private global::Gtk.VBox vbox6;

	private global::Gtk.HBox hbox13;

	private global::Gtk.Label label9;

	private global::Gtk.Button button12;

	private global::Gtk.HBox hbox14;

	private global::Gtk.Label label11;

	private global::Gtk.Button button13;

	private global::Gtk.HBox hbox10;

	private global::Gtk.Label label8;

	private global::Gtk.Button button4;

	private global::Gtk.HBox hbox11;

	private global::Gtk.Label label14;

	private global::Gtk.Button button8;

	private global::Gtk.Button button9;

	private global::Gtk.HBox hbox12;

	private global::Gtk.Label label15;

	private global::Gtk.Button button10;

	private global::Gtk.Button button11;

	private global::Gtk.HBox hbox5;

	private global::Gtk.VBox vbox8;

	private global::Gtk.Label label17;

	private global::Gtk.Label label10;

	private global::Gtk.Button button5;

	private global::Gtk.HBox hbox6;

	private global::Gtk.VBox vbox9;

	private global::Gtk.Label label18;

	private global::Gtk.VBox vbox5;

	private global::Gtk.HBox hbox8;

	private global::Gtk.Label label13;

	private global::Gtk.Button button7;

	private global::Gtk.HBox hbox9;

	private global::Gtk.Label label12;

	private global::Gtk.Button button6;

	private global::Gtk.Label GtkLabel15;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("Scigeobib");
		this.WindowPosition = ((global::Gtk.WindowPosition)(1));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox1 = new global::Gtk.VBox();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.frame_input = new global::Gtk.Frame();
		this.frame_input.Name = "frame_input";
		this.frame_input.ShadowType = ((global::Gtk.ShadowType)(0));
		// Container child frame_input.Gtk.Container+ContainerChild
		this.GtkAlignment = new global::Gtk.Alignment(0F, 0F, 1F, 1F);
		this.GtkAlignment.Name = "GtkAlignment";
		this.GtkAlignment.LeftPadding = ((uint)(12));
		// Container child GtkAlignment.Gtk.Container+ContainerChild
		this.vbox2 = new global::Gtk.VBox();
		this.vbox2.Name = "vbox2";
		this.vbox2.Spacing = 6;
		// Container child vbox2.Gtk.Box+BoxChild
		this.hbox1 = new global::Gtk.HBox();
		this.hbox1.Spacing = 6;
		// Container child hbox1.Gtk.Box+BoxChild
		this.label3 = new global::Gtk.Label();
		this.label3.Name = "label3";
		this.label3.LabelProp = global::Mono.Unix.Catalog.GetString("<b>A</b>");
		this.label3.UseMarkup = true;
		this.hbox1.Add(this.label3);
		global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.label3]));
		w1.Position = 0;
		w1.Expand = false;
		w1.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.label1 = new global::Gtk.Label();
		this.label1.Name = "label1";
		this.label1.LabelProp = global::Mono.Unix.Catalog.GetString("Publications (WOS or Scopus CSV):");
		this.hbox1.Add(this.label1);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.label1]));
		w2.Position = 1;
		w2.Expand = false;
		w2.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.inputPublications = new global::Gtk.Entry();
		this.inputPublications.CanFocus = true;
		this.inputPublications.Name = "inputPublications";
		this.inputPublications.IsEditable = true;
		this.inputPublications.InvisibleChar = '●';
		this.hbox1.Add(this.inputPublications);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.inputPublications]));
		w3.Position = 2;
		// Container child hbox1.Gtk.Box+BoxChild
		this.inputPublicationsSelect = new global::Gtk.Button();
		this.inputPublicationsSelect.CanFocus = true;
		this.inputPublicationsSelect.Name = "inputPublicationsSelect";
		this.inputPublicationsSelect.UseUnderline = true;
		this.inputPublicationsSelect.Label = global::Mono.Unix.Catalog.GetString("Select");
		this.hbox1.Add(this.inputPublicationsSelect);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.inputPublicationsSelect]));
		w4.Position = 3;
		w4.Expand = false;
		w4.Fill = false;
		this.vbox2.Add(this.hbox1);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.hbox1]));
		w5.Position = 0;
		w5.Expand = false;
		w5.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.hbox2 = new global::Gtk.HBox();
		this.hbox2.Name = "hbox2";
		this.hbox2.Spacing = 6;
		// Container child hbox2.Gtk.Box+BoxChild
		this.label4 = new global::Gtk.Label();
		this.label4.Name = "label4";
		this.label4.LabelProp = global::Mono.Unix.Catalog.GetString("<b>B</b>");
		this.label4.UseMarkup = true;
		this.hbox2.Add(this.label4);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.label4]));
		w6.Position = 0;
		w6.Expand = false;
		w6.Fill = false;
		// Container child hbox2.Gtk.Box+BoxChild
		this.label2 = new global::Gtk.Label();
		this.label2.Name = "label2";
		this.label2.LabelProp = global::Mono.Unix.Catalog.GetString("Geo coded locations CSV (from previous run Output B):");
		this.hbox2.Add(this.label2);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.label2]));
		w7.Position = 1;
		w7.Expand = false;
		w7.Fill = false;
		// Container child hbox2.Gtk.Box+BoxChild
		this.inputKnownLocations = new global::Gtk.Entry();
		this.inputKnownLocations.CanFocus = true;
		this.inputKnownLocations.Name = "inputKnownLocations";
		this.inputKnownLocations.IsEditable = true;
		this.inputKnownLocations.InvisibleChar = '●';
		this.hbox2.Add(this.inputKnownLocations);
		global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.inputKnownLocations]));
		w8.Position = 2;
		// Container child hbox2.Gtk.Box+BoxChild
		this.inputKnownLocationsSelect = new global::Gtk.Button();
		this.inputKnownLocationsSelect.CanFocus = true;
		this.inputKnownLocationsSelect.Name = "inputKnownLocationsSelect";
		this.inputKnownLocationsSelect.UseUnderline = true;
		this.inputKnownLocationsSelect.Label = global::Mono.Unix.Catalog.GetString("Select");
		this.hbox2.Add(this.inputKnownLocationsSelect);
		global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.inputKnownLocationsSelect]));
		w9.Position = 3;
		w9.Expand = false;
		w9.Fill = false;
		this.vbox2.Add(this.hbox2);
		global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.hbox2]));
		w10.Position = 1;
		w10.Expand = false;
		w10.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.hbox3 = new global::Gtk.HBox();
		this.hbox3.Name = "hbox3";
		this.hbox3.Spacing = 6;
		// Container child hbox3.Gtk.Box+BoxChild
		this.label5 = new global::Gtk.Label();
		this.label5.Name = "label5";
		this.label5.LabelProp = global::Mono.Unix.Catalog.GetString("<b>C</b>");
		this.label5.UseMarkup = true;
		this.hbox3.Add(this.label5);
		global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.label5]));
		w11.Position = 0;
		w11.Expand = false;
		w11.Fill = false;
		// Container child hbox3.Gtk.Box+BoxChild
		this.label6 = new global::Gtk.Label();
		this.label6.Name = "label6";
		this.label6.LabelProp = global::Mono.Unix.Catalog.GetString("Bing maps API key (geo code unknown locations using this):");
		this.hbox3.Add(this.label6);
		global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.label6]));
		w12.Position = 1;
		w12.Expand = false;
		w12.Fill = false;
		// Container child hbox3.Gtk.Box+BoxChild
		this.inputGeoCoderKey = new global::Gtk.Entry();
		this.inputGeoCoderKey.CanFocus = true;
		this.inputGeoCoderKey.Name = "inputGeoCoderKey";
		this.inputGeoCoderKey.IsEditable = true;
		this.inputGeoCoderKey.InvisibleChar = '●';
		this.hbox3.Add(this.inputGeoCoderKey);
		global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.inputGeoCoderKey]));
		w13.Position = 2;
		// Container child hbox3.Gtk.Box+BoxChild
		this.inputRetryGeoCoding = new global::Gtk.CheckButton();
		this.inputRetryGeoCoding.CanFocus = true;
		this.inputRetryGeoCoding.Name = "inputRetryGeoCoding";
		this.inputRetryGeoCoding.Label = global::Mono.Unix.Catalog.GetString("Retry geo coding of previously failed");
		this.inputRetryGeoCoding.DrawIndicator = true;
		this.inputRetryGeoCoding.UseUnderline = true;
		this.hbox3.Add(this.inputRetryGeoCoding);
		global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.inputRetryGeoCoding]));
		w14.Position = 3;
		this.vbox2.Add(this.hbox3);
		global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.hbox3]));
		w15.Position = 2;
		w15.Expand = false;
		w15.Fill = false;
		this.GtkAlignment.Add(this.vbox2);
		this.frame_input.Add(this.GtkAlignment);
		this.GtkLabel3 = new global::Gtk.Label();
		this.GtkLabel3.Name = "GtkLabel3";
		this.GtkLabel3.LabelProp = global::Mono.Unix.Catalog.GetString("<b>Input</b>");
		this.GtkLabel3.UseMarkup = true;
		this.frame_input.LabelWidget = this.GtkLabel3;
		this.vbox1.Add(this.frame_input);
		global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.frame_input]));
		w18.Position = 0;
		w18.Expand = false;
		w18.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.frame3 = new global::Gtk.Frame();
		this.frame3.Name = "frame3";
		this.frame3.ShadowType = ((global::Gtk.ShadowType)(0));
		// Container child frame3.Gtk.Container+ContainerChild
		this.GtkAlignment1 = new global::Gtk.Alignment(0F, 0F, 1F, 1F);
		this.GtkAlignment1.Name = "GtkAlignment1";
		this.GtkAlignment1.LeftPadding = ((uint)(12));
		// Container child GtkAlignment1.Gtk.Container+ContainerChild
		this.vbox3 = new global::Gtk.VBox();
		this.vbox3.Name = "vbox3";
		this.vbox3.Spacing = 6;
		// Container child vbox3.Gtk.Box+BoxChild
		this.hbox7 = new global::Gtk.HBox();
		this.hbox7.Name = "hbox7";
		this.hbox7.Spacing = 6;
		// Container child hbox7.Gtk.Box+BoxChild
		this.buttonStart = new global::Gtk.Button();
		this.buttonStart.CanFocus = true;
		this.buttonStart.Name = "buttonStart";
		this.buttonStart.UseUnderline = true;
		this.buttonStart.Label = global::Mono.Unix.Catalog.GetString("Start");
		this.hbox7.Add(this.buttonStart);
		global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.hbox7[this.buttonStart]));
		w19.Position = 0;
		w19.Expand = false;
		w19.Fill = false;
		// Container child hbox7.Gtk.Box+BoxChild
		this.buttonStop = new global::Gtk.Button();
		this.buttonStop.CanFocus = true;
		this.buttonStop.Name = "buttonStop";
		this.buttonStop.UseUnderline = true;
		this.buttonStop.Label = global::Mono.Unix.Catalog.GetString("Stop");
		this.hbox7.Add(this.buttonStop);
		global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.hbox7[this.buttonStop]));
		w20.Position = 1;
		w20.Expand = false;
		w20.Fill = false;
		this.vbox3.Add(this.hbox7);
		global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.hbox7]));
		w21.Position = 0;
		w21.Expand = false;
		w21.Fill = false;
		// Container child vbox3.Gtk.Box+BoxChild
		this.GtkScrolledWindow = new global::Gtk.ScrolledWindow();
		this.GtkScrolledWindow.Name = "GtkScrolledWindow";
		this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
		this.messages = new global::Gtk.TextView();
		this.messages.CanFocus = true;
		this.messages.Name = "messages";
		this.messages.Editable = false;
		this.GtkScrolledWindow.Add(this.messages);
		this.vbox3.Add(this.GtkScrolledWindow);
		global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.GtkScrolledWindow]));
		w23.Position = 1;
		this.GtkAlignment1.Add(this.vbox3);
		this.frame3.Add(this.GtkAlignment1);
		this.GtkLabel6 = new global::Gtk.Label();
		this.GtkLabel6.Name = "GtkLabel6";
		this.GtkLabel6.LabelProp = global::Mono.Unix.Catalog.GetString("<b>Progress</b>");
		this.GtkLabel6.UseMarkup = true;
		this.frame3.LabelWidget = this.GtkLabel6;
		this.vbox1.Add(this.frame3);
		global::Gtk.Box.BoxChild w26 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.frame3]));
		w26.Position = 1;
		// Container child vbox1.Gtk.Box+BoxChild
		this.frame_output = new global::Gtk.Frame();
		this.frame_output.Name = "frame_output";
		this.frame_output.ShadowType = ((global::Gtk.ShadowType)(0));
		// Container child frame_output.Gtk.Container+ContainerChild
		this.GtkAlignment2 = new global::Gtk.Alignment(0F, 0F, 1F, 1F);
		this.GtkAlignment2.Name = "GtkAlignment2";
		this.GtkAlignment2.LeftPadding = ((uint)(12));
		// Container child GtkAlignment2.Gtk.Container+ContainerChild
		this.vbox4 = new global::Gtk.VBox();
		this.vbox4.Name = "vbox4";
		this.vbox4.Spacing = 6;
		// Container child vbox4.Gtk.Box+BoxChild
		this.hbox4 = new global::Gtk.HBox();
		this.hbox4.Name = "hbox4";
		this.hbox4.Spacing = 6;
		// Container child hbox4.Gtk.Box+BoxChild
		this.vbox7 = new global::Gtk.VBox();
		this.vbox7.Name = "vbox7";
		this.vbox7.Spacing = 6;
		// Container child vbox7.Gtk.Box+BoxChild
		this.label16 = new global::Gtk.Label();
		this.label16.Name = "label16";
		this.label16.LabelProp = global::Mono.Unix.Catalog.GetString("<b>A</b>");
		this.label16.UseMarkup = true;
		this.vbox7.Add(this.label16);
		global::Gtk.Box.BoxChild w27 = ((global::Gtk.Box.BoxChild)(this.vbox7[this.label16]));
		w27.Position = 0;
		w27.Expand = false;
		w27.Fill = false;
		this.hbox4.Add(this.vbox7);
		global::Gtk.Box.BoxChild w28 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.vbox7]));
		w28.Position = 0;
		w28.Expand = false;
		w28.Fill = false;
		// Container child hbox4.Gtk.Box+BoxChild
		this.vbox6 = new global::Gtk.VBox();
		this.vbox6.Name = "vbox6";
		this.vbox6.Spacing = 6;
		// Container child vbox6.Gtk.Box+BoxChild
		this.hbox13 = new global::Gtk.HBox();
		this.hbox13.Name = "hbox13";
		this.hbox13.Spacing = 6;
		// Container child hbox13.Gtk.Box+BoxChild
		this.label9 = new global::Gtk.Label();
		this.label9.Name = "label9";
		this.label9.LabelProp = global::Mono.Unix.Catalog.GetString("Collaboration KML by city");
		this.hbox13.Add(this.label9);
		global::Gtk.Box.BoxChild w29 = ((global::Gtk.Box.BoxChild)(this.hbox13[this.label9]));
		w29.Position = 0;
		w29.Expand = false;
		w29.Fill = false;
		// Container child hbox13.Gtk.Box+BoxChild
		this.button12 = new global::Gtk.Button();
		this.button12.CanFocus = true;
		this.button12.Name = "button12";
		this.button12.UseUnderline = true;
		this.button12.Label = global::Mono.Unix.Catalog.GetString("To KML file");
		this.hbox13.Add(this.button12);
		global::Gtk.Box.BoxChild w30 = ((global::Gtk.Box.BoxChild)(this.hbox13[this.button12]));
		w30.Position = 1;
		w30.Expand = false;
		w30.Fill = false;
		this.vbox6.Add(this.hbox13);
		global::Gtk.Box.BoxChild w31 = ((global::Gtk.Box.BoxChild)(this.vbox6[this.hbox13]));
		w31.Position = 0;
		w31.Expand = false;
		w31.Fill = false;
		// Container child vbox6.Gtk.Box+BoxChild
		this.hbox14 = new global::Gtk.HBox();
		this.hbox14.Name = "hbox14";
		this.hbox14.Spacing = 6;
		// Container child hbox14.Gtk.Box+BoxChild
		this.label11 = new global::Gtk.Label();
		this.label11.Name = "label11";
		this.label11.LabelProp = global::Mono.Unix.Catalog.GetString("Collaboration KML by country");
		this.hbox14.Add(this.label11);
		global::Gtk.Box.BoxChild w32 = ((global::Gtk.Box.BoxChild)(this.hbox14[this.label11]));
		w32.Position = 0;
		w32.Expand = false;
		w32.Fill = false;
		// Container child hbox14.Gtk.Box+BoxChild
		this.button13 = new global::Gtk.Button();
		this.button13.CanFocus = true;
		this.button13.Name = "button13";
		this.button13.UseUnderline = true;
		this.button13.Label = global::Mono.Unix.Catalog.GetString("To KML file");
		this.hbox14.Add(this.button13);
		global::Gtk.Box.BoxChild w33 = ((global::Gtk.Box.BoxChild)(this.hbox14[this.button13]));
		w33.Position = 1;
		w33.Expand = false;
		w33.Fill = false;
		this.vbox6.Add(this.hbox14);
		global::Gtk.Box.BoxChild w34 = ((global::Gtk.Box.BoxChild)(this.vbox6[this.hbox14]));
		w34.Position = 1;
		w34.Expand = false;
		w34.Fill = false;
		// Container child vbox6.Gtk.Box+BoxChild
		this.hbox10 = new global::Gtk.HBox();
		this.hbox10.Name = "hbox10";
		this.hbox10.Spacing = 6;
		// Container child hbox10.Gtk.Box+BoxChild
		this.label8 = new global::Gtk.Label();
		this.label8.Name = "label8";
		this.label8.LabelProp = global::Mono.Unix.Catalog.GetString("Collaboration KML by institution");
		this.hbox10.Add(this.label8);
		global::Gtk.Box.BoxChild w35 = ((global::Gtk.Box.BoxChild)(this.hbox10[this.label8]));
		w35.Position = 0;
		w35.Expand = false;
		w35.Fill = false;
		// Container child hbox10.Gtk.Box+BoxChild
		this.button4 = new global::Gtk.Button();
		this.button4.CanFocus = true;
		this.button4.Name = "button4";
		this.button4.UseUnderline = true;
		this.button4.Label = global::Mono.Unix.Catalog.GetString("To KML file");
		this.hbox10.Add(this.button4);
		global::Gtk.Box.BoxChild w36 = ((global::Gtk.Box.BoxChild)(this.hbox10[this.button4]));
		w36.Position = 1;
		w36.Expand = false;
		w36.Fill = false;
		this.vbox6.Add(this.hbox10);
		global::Gtk.Box.BoxChild w37 = ((global::Gtk.Box.BoxChild)(this.vbox6[this.hbox10]));
		w37.Position = 2;
		w37.Expand = false;
		w37.Fill = false;
		// Container child vbox6.Gtk.Box+BoxChild
		this.hbox11 = new global::Gtk.HBox();
		this.hbox11.Name = "hbox11";
		this.hbox11.Spacing = 6;
		// Container child hbox11.Gtk.Box+BoxChild
		this.label14 = new global::Gtk.Label();
		this.label14.Name = "label14";
		this.label14.LabelProp = global::Mono.Unix.Catalog.GetString("Publications in countries");
		this.hbox11.Add(this.label14);
		global::Gtk.Box.BoxChild w38 = ((global::Gtk.Box.BoxChild)(this.hbox11[this.label14]));
		w38.Position = 0;
		w38.Expand = false;
		w38.Fill = false;
		// Container child hbox11.Gtk.Box+BoxChild
		this.button8 = new global::Gtk.Button();
		this.button8.CanFocus = true;
		this.button8.Name = "button8";
		this.button8.UseUnderline = true;
		this.button8.Label = global::Mono.Unix.Catalog.GetString("To KML file");
		this.hbox11.Add(this.button8);
		global::Gtk.Box.BoxChild w39 = ((global::Gtk.Box.BoxChild)(this.hbox11[this.button8]));
		w39.Position = 1;
		w39.Expand = false;
		w39.Fill = false;
		// Container child hbox11.Gtk.Box+BoxChild
		this.button9 = new global::Gtk.Button();
		this.button9.CanFocus = true;
		this.button9.Name = "button9";
		this.button9.UseUnderline = true;
		this.button9.Label = global::Mono.Unix.Catalog.GetString("To CSV file");
		this.hbox11.Add(this.button9);
		global::Gtk.Box.BoxChild w40 = ((global::Gtk.Box.BoxChild)(this.hbox11[this.button9]));
		w40.Position = 2;
		w40.Expand = false;
		w40.Fill = false;
		this.vbox6.Add(this.hbox11);
		global::Gtk.Box.BoxChild w41 = ((global::Gtk.Box.BoxChild)(this.vbox6[this.hbox11]));
		w41.Position = 3;
		w41.Expand = false;
		w41.Fill = false;
		// Container child vbox6.Gtk.Box+BoxChild
		this.hbox12 = new global::Gtk.HBox();
		this.hbox12.Name = "hbox12";
		this.hbox12.Spacing = 6;
		// Container child hbox12.Gtk.Box+BoxChild
		this.label15 = new global::Gtk.Label();
		this.label15.Name = "label15";
		this.label15.LabelProp = global::Mono.Unix.Catalog.GetString("Journals in countries");
		this.hbox12.Add(this.label15);
		global::Gtk.Box.BoxChild w42 = ((global::Gtk.Box.BoxChild)(this.hbox12[this.label15]));
		w42.Position = 0;
		w42.Expand = false;
		w42.Fill = false;
		// Container child hbox12.Gtk.Box+BoxChild
		this.button10 = new global::Gtk.Button();
		this.button10.CanFocus = true;
		this.button10.Name = "button10";
		this.button10.UseUnderline = true;
		this.button10.Label = global::Mono.Unix.Catalog.GetString("To KML file");
		this.hbox12.Add(this.button10);
		global::Gtk.Box.BoxChild w43 = ((global::Gtk.Box.BoxChild)(this.hbox12[this.button10]));
		w43.Position = 1;
		w43.Expand = false;
		w43.Fill = false;
		// Container child hbox12.Gtk.Box+BoxChild
		this.button11 = new global::Gtk.Button();
		this.button11.CanFocus = true;
		this.button11.Name = "button11";
		this.button11.UseUnderline = true;
		this.button11.Label = global::Mono.Unix.Catalog.GetString("To CSV file");
		this.hbox12.Add(this.button11);
		global::Gtk.Box.BoxChild w44 = ((global::Gtk.Box.BoxChild)(this.hbox12[this.button11]));
		w44.Position = 2;
		w44.Expand = false;
		w44.Fill = false;
		this.vbox6.Add(this.hbox12);
		global::Gtk.Box.BoxChild w45 = ((global::Gtk.Box.BoxChild)(this.vbox6[this.hbox12]));
		w45.Position = 4;
		w45.Expand = false;
		w45.Fill = false;
		this.hbox4.Add(this.vbox6);
		global::Gtk.Box.BoxChild w46 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.vbox6]));
		w46.Position = 1;
		w46.Expand = false;
		w46.Fill = false;
		this.vbox4.Add(this.hbox4);
		global::Gtk.Box.BoxChild w47 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.hbox4]));
		w47.Position = 0;
		w47.Expand = false;
		w47.Fill = false;
		// Container child vbox4.Gtk.Box+BoxChild
		this.hbox5 = new global::Gtk.HBox();
		this.hbox5.Name = "hbox5";
		this.hbox5.Spacing = 6;
		// Container child hbox5.Gtk.Box+BoxChild
		this.vbox8 = new global::Gtk.VBox();
		this.vbox8.Name = "vbox8";
		this.vbox8.Spacing = 6;
		// Container child vbox8.Gtk.Box+BoxChild
		this.label17 = new global::Gtk.Label();
		this.label17.Name = "label17";
		this.label17.LabelProp = global::Mono.Unix.Catalog.GetString("<b>B</b>");
		this.label17.UseMarkup = true;
		this.vbox8.Add(this.label17);
		global::Gtk.Box.BoxChild w48 = ((global::Gtk.Box.BoxChild)(this.vbox8[this.label17]));
		w48.Position = 0;
		w48.Expand = false;
		w48.Fill = false;
		this.hbox5.Add(this.vbox8);
		global::Gtk.Box.BoxChild w49 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.vbox8]));
		w49.Position = 0;
		w49.Expand = false;
		w49.Fill = false;
		// Container child hbox5.Gtk.Box+BoxChild
		this.label10 = new global::Gtk.Label();
		this.label10.Name = "label10";
		this.label10.LabelProp = global::Mono.Unix.Catalog.GetString("Geo coded locations CSV (Input B + newly geo coded using Input C)");
		this.hbox5.Add(this.label10);
		global::Gtk.Box.BoxChild w50 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.label10]));
		w50.Position = 1;
		w50.Expand = false;
		w50.Fill = false;
		// Container child hbox5.Gtk.Box+BoxChild
		this.button5 = new global::Gtk.Button();
		this.button5.CanFocus = true;
		this.button5.Name = "button5";
		this.button5.UseUnderline = true;
		this.button5.Label = global::Mono.Unix.Catalog.GetString("To file");
		this.hbox5.Add(this.button5);
		global::Gtk.Box.BoxChild w51 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.button5]));
		w51.Position = 2;
		w51.Expand = false;
		w51.Fill = false;
		this.vbox4.Add(this.hbox5);
		global::Gtk.Box.BoxChild w52 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.hbox5]));
		w52.Position = 1;
		w52.Expand = false;
		w52.Fill = false;
		// Container child vbox4.Gtk.Box+BoxChild
		this.hbox6 = new global::Gtk.HBox();
		this.hbox6.Name = "hbox6";
		this.hbox6.Spacing = 6;
		// Container child hbox6.Gtk.Box+BoxChild
		this.vbox9 = new global::Gtk.VBox();
		this.vbox9.Name = "vbox9";
		this.vbox9.Spacing = 6;
		// Container child vbox9.Gtk.Box+BoxChild
		this.label18 = new global::Gtk.Label();
		this.label18.Name = "label18";
		this.label18.LabelProp = global::Mono.Unix.Catalog.GetString("<b>C</b>");
		this.label18.UseMarkup = true;
		this.vbox9.Add(this.label18);
		global::Gtk.Box.BoxChild w53 = ((global::Gtk.Box.BoxChild)(this.vbox9[this.label18]));
		w53.Position = 0;
		w53.Expand = false;
		w53.Fill = false;
		this.hbox6.Add(this.vbox9);
		global::Gtk.Box.BoxChild w54 = ((global::Gtk.Box.BoxChild)(this.hbox6[this.vbox9]));
		w54.Position = 0;
		w54.Expand = false;
		w54.Fill = false;
		// Container child hbox6.Gtk.Box+BoxChild
		this.vbox5 = new global::Gtk.VBox();
		this.vbox5.Name = "vbox5";
		this.vbox5.Spacing = 6;
		// Container child vbox5.Gtk.Box+BoxChild
		this.hbox8 = new global::Gtk.HBox();
		this.hbox8.Name = "hbox8";
		this.hbox8.Spacing = 6;
		// Container child hbox8.Gtk.Box+BoxChild
		this.label13 = new global::Gtk.Label();
		this.label13.Name = "label13";
		this.label13.LabelProp = global::Mono.Unix.Catalog.GetString("List of geo coded locations which failed to geo code successfully");
		this.hbox8.Add(this.label13);
		global::Gtk.Box.BoxChild w55 = ((global::Gtk.Box.BoxChild)(this.hbox8[this.label13]));
		w55.Position = 0;
		w55.Expand = false;
		w55.Fill = false;
		// Container child hbox8.Gtk.Box+BoxChild
		this.button7 = new global::Gtk.Button();
		this.button7.CanFocus = true;
		this.button7.Name = "button7";
		this.button7.UseUnderline = true;
		this.button7.Label = global::Mono.Unix.Catalog.GetString("To file");
		this.hbox8.Add(this.button7);
		global::Gtk.Box.BoxChild w56 = ((global::Gtk.Box.BoxChild)(this.hbox8[this.button7]));
		w56.Position = 1;
		w56.Expand = false;
		w56.Fill = false;
		this.vbox5.Add(this.hbox8);
		global::Gtk.Box.BoxChild w57 = ((global::Gtk.Box.BoxChild)(this.vbox5[this.hbox8]));
		w57.Position = 0;
		w57.Expand = false;
		w57.Fill = false;
		// Container child vbox5.Gtk.Box+BoxChild
		this.hbox9 = new global::Gtk.HBox();
		this.hbox9.Name = "hbox9";
		this.hbox9.Spacing = 6;
		// Container child hbox9.Gtk.Box+BoxChild
		this.label12 = new global::Gtk.Label();
		this.label12.Name = "label12";
		this.label12.LabelProp = global::Mono.Unix.Catalog.GetString("List of locations not geo coded yet");
		this.hbox9.Add(this.label12);
		global::Gtk.Box.BoxChild w58 = ((global::Gtk.Box.BoxChild)(this.hbox9[this.label12]));
		w58.Position = 0;
		w58.Expand = false;
		w58.Fill = false;
		// Container child hbox9.Gtk.Box+BoxChild
		this.button6 = new global::Gtk.Button();
		this.button6.CanFocus = true;
		this.button6.Name = "button6";
		this.button6.UseUnderline = true;
		this.button6.Label = global::Mono.Unix.Catalog.GetString("To file");
		this.hbox9.Add(this.button6);
		global::Gtk.Box.BoxChild w59 = ((global::Gtk.Box.BoxChild)(this.hbox9[this.button6]));
		w59.Position = 1;
		w59.Expand = false;
		w59.Fill = false;
		this.vbox5.Add(this.hbox9);
		global::Gtk.Box.BoxChild w60 = ((global::Gtk.Box.BoxChild)(this.vbox5[this.hbox9]));
		w60.Position = 1;
		w60.Expand = false;
		w60.Fill = false;
		this.hbox6.Add(this.vbox5);
		global::Gtk.Box.BoxChild w61 = ((global::Gtk.Box.BoxChild)(this.hbox6[this.vbox5]));
		w61.Position = 1;
		w61.Expand = false;
		w61.Fill = false;
		this.vbox4.Add(this.hbox6);
		global::Gtk.Box.BoxChild w62 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.hbox6]));
		w62.Position = 2;
		w62.Expand = false;
		w62.Fill = false;
		this.GtkAlignment2.Add(this.vbox4);
		this.frame_output.Add(this.GtkAlignment2);
		this.GtkLabel15 = new global::Gtk.Label();
		this.GtkLabel15.Name = "GtkLabel15";
		this.GtkLabel15.LabelProp = global::Mono.Unix.Catalog.GetString("<b>Output</b>");
		this.GtkLabel15.UseMarkup = true;
		this.frame_output.LabelWidget = this.GtkLabel15;
		this.vbox1.Add(this.frame_output);
		global::Gtk.Box.BoxChild w65 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.frame_output]));
		w65.Position = 2;
		w65.Expand = false;
		w65.Fill = false;
		this.Add(this.vbox1);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 768;
		this.DefaultHeight = 468;
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
		this.inputPublicationsSelect.Clicked += new global::System.EventHandler(this.OnInputPublicationsSelect);
		this.inputKnownLocationsSelect.Clicked += new global::System.EventHandler(this.OnInputKnownLocationsSelect);
		this.buttonStart.Clicked += new global::System.EventHandler(this.OnButtonStart);
		this.buttonStop.Clicked += new global::System.EventHandler(this.OnButtonStop);
		this.button12.Clicked += new global::System.EventHandler(this.OnOutputCollaborationsByCityKml);
		this.button13.Clicked += new global::System.EventHandler(this.OnOutputCollaborationsByCountryKml);
		this.button4.Clicked += new global::System.EventHandler(this.OnOutputCollaborationsByInstitutionKml);
		this.button8.Clicked += new global::System.EventHandler(this.OnOutputPublicationsKml);
		this.button9.Clicked += new global::System.EventHandler(this.OnOutputPublicationsCsv);
		this.button10.Clicked += new global::System.EventHandler(this.OnOutputJournalsKml);
		this.button11.Clicked += new global::System.EventHandler(this.OnOutputJournalsCsv);
		this.button5.Clicked += new global::System.EventHandler(this.OnOutputKnownLocations);
		this.button7.Clicked += new global::System.EventHandler(this.OnOutputFailedLocations);
		this.button6.Clicked += new global::System.EventHandler(this.OnOutputUnknownLocations);
	}
}
